apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: platform-postgres-lidarr-log
  annotations:
    argocd.argoproj.io/sync-wave: "35"
spec:
  name: lidarr-log
  owner: lidarr
  databaseReclaimPolicy: retain
  cluster:
    name: platform-postgres
