apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore

  target:
    name: authentik-secrets
    creationPolicy: Owner

  data:
    - secretKey: AUTHENTIK_SECRET_KEY
      remoteRef:
        key: AUTHENTIK_SECRET_KEY

    - secretKey: AUTHENTIK_BOOTSTRAP_PASSWORD
      remoteRef:
        key: AUTHENTIK_BOOTSTRAP_PASSWORD

    - secretKey: AUTHENTIK_POSTGRESQL__PASSWORD
      remoteRef:
        key: AUTHENTIK_POSTGRES_PASSWORD

    - secretKey: AUTHENTIK_ARGOCD_CLIENT_SECRET
      remoteRef:
        key: AUTHENTIK_ARGOCD_CLIENT_SECRET
