apiVersion: v1
kind: ConfigMap
metadata:
  name: authentik-blueprint-groups
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
data:
  groups.yaml: |
    version: 1
    metadata:
      name: Homelab groups
      labels:
        blueprints.goauthentik.io/instantiate: "true"
    entries:
      - model: authentik_core.group
        state: present
        identifiers:
          name: ArgoCD Admins
        attrs:
          name: ArgoCD Admins
          is_superuser: false
          users:
            - !Find [authentik_core.user, [username, akadmin]]

      - model: authentik_core.group
        state: present
        identifiers:
          name: ArgoCD Viewers
        attrs:
          name: ArgoCD Viewers
          is_superuser: false

      - model: authentik_core.group
        state: present
        identifiers:
          name: Homelab Admins
        attrs:
          name: Homelab Admins
          is_superuser: true

      - model: authentik_core.group
        state: present
        identifiers:
          name: Homelab Users
        attrs:
          name: Homelab Users
          is_superuser: false
