apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: authentik

resources:
  - external-secret.yaml
  - groups-blueprint.yaml
  - argocd-blueprint.yaml
  - bentopdf-blueprint.yaml
  - sonarr-blueprint.yaml
  - radarr-blueprint.yaml
  - lidarr-blueprint.yaml
  - prowlarr-blueprint.yaml
  - bazarr-blueprint.yaml
  - qbittorrent-blueprint.yaml
  - cleanuparr-blueprint.yaml
  - proxy-outpost-blueprint.yaml
  - bentopdf-reference-grant.yaml
  - qbittorrent-reference-grant.yaml
  - servarr-reference-grant.yaml

helmCharts:
  - name: authentik
    repo: https://charts.goauthentik.io
    version: 2026.8.0
    releaseName: authentik
    namespace: authentik
    valuesFile: values.yaml
