apiVersion: gateway.networking.k8s.io/v1
kind: ReferenceGrant
metadata:
  name: qbittorrent-to-authentik
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: qbittorrent-vpn
  to:
    - group: ""
      kind: Service
      name: authentik-server
