apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: platform-postgres
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  instances: 2

  managed:
    roles:
      - name: authentik
        ensure: present
        inherit: true
        comment: Authentik application role
        connectionLimit: -1
        login: true
        superuser: false
        createdb: false
        createrole: false
        passwordSecret:
          name: authentik-postgres
      - name: cleanuparr
        ensure: present
        inherit: true
        comment: Cleanuparr application role
        connectionLimit: -1
        login: true
        superuser: false
        createdb: false
        createrole: false
        passwordSecret:
          name: cleanuparr-postgres
      - name: lidarr
        ensure: present
        inherit: true
        comment: Lidarr application role
        connectionLimit: -1
        login: true
        superuser: false
        createdb: false
        createrole: false
        passwordSecret:
          name: lidarr-postgres
      - name: radarr
        ensure: present
        inherit: true
        comment: Radarr application role
        connectionLimit: -1
        login: true
        superuser: false
        createdb: false
        createrole: false
        passwordSecret:
          name: radarr-postgres

  plugins:
    - enabled: true
      name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: platform-postgres-b2

  storage:
    storageClass: synology-csi-iscsi-retain
    size: 20Gi

  backup:
    target: prefer-standby
    volumeSnapshot:
      className: synology-csi-retain
      online: true
