apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: platform-postgres-prowlarr-log
  annotations:
    argocd.argoproj.io/sync-wave: "35"
spec:
  name: prowlarr-log
  owner: prowlarr
  databaseReclaimPolicy: retain
  cluster:
    name: platform-postgres
