apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: prowlarr-postgres
  annotations:
    argocd.argoproj.io/sync-wave: "15"
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore

  target:
    name: prowlarr-postgres
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: prowlarr
        password: "{{ .password }}"

  data:
    - secretKey: password
      remoteRef:
        key: PROWLARR_POSTGRES_PASSWORD
