installCRDs: true

bitwarden-sdk-server:
  enabled: true

  deploymentAnnotations:
    argocd.argoproj.io/sync-wave: "25"
    reloader.stakater.com/auto: "true"

  podSecurityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault

  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 65532
    runAsGroup: 65532

  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      memory: 256Mi

resources:
  requests:
    cpu: 10m
    memory: 64Mi
  limits:
    memory: 192Mi

webhook:
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      memory: 96Mi

certController:
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      memory: 192Mi

serviceMonitor:
  enabled: false
