apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: proton-vpn-wireguard
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore

  target:
    name: proton-vpn-wireguard
    creationPolicy: Owner

  data:
    - secretKey: WIREGUARD_PRIVATE_KEY
      remoteRef:
        key: PROTON_VPN_WIREGUARD_PRIVATE_KEY
