apiVersion: v1
kind: PersistentVolume
metadata:
  name: servarr-media
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  volumeMode: Filesystem
  mountOptions:
    - nfsvers=4.1
    - hard
    - noatime
  nfs:
    server: 10.250.0.2
    path: /volume1/media
