apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - git:
        repoURL: git@github.com:bartoszkiljanski/homelab-platform.git
        revision: main
        directories:
          - path: k8s/talos/apps/*
  template:
    metadata:
      name: "{{ .path.basename }}"
      namespace: argocd
    spec:
      project: apps
      source:
        repoURL: git@github.com:bartoszkiljanski/homelab-platform.git
        targetRevision: main
        path: "{{ .path.path }}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{ .path.basename }}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - ApplyOutOfSyncOnly=true
          - CreateNamespace=true
          - PruneLast=true
          - RespectIgnoreDifferences=true
          - ServerSideApply=true
