apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infra
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - git:
        repoURL: git@github.com:bartoszkiljanski/homelab-platform.git
        revision: main
        directories:
          - path: k8s/talos/infra/*
  template:
    metadata:
      name: "{{ .path.basename }}"
      namespace: argocd
    spec:
      project: infra
      source:
        repoURL: git@github.com:bartoszkiljanski/homelab-platform.git
        targetRevision: main
        path: "{{ .path.path }}"
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ if or (eq .path.basename "cilium") (eq .path.basename "metrics-server") }}kube-system{{ else }}{{ .path.basename }}{{ end }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - ApplyOutOfSyncOnly=true
          - CreateNamespace=true
          - PruneLast=true
          - RespectIgnoreDifferences=true
          - ServerSideApply=true
