replicaCount: 1

image:
  repository: ghcr.io/alam00000/bentopdf-simple
  tag: 2.8.7

serviceAccount:
  create: true
  automountServiceAccountToken: false

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

ingress:
  enabled: false

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    memory: 256Mi
